name: Deploy Storage Account

on: workflow_dispatch

permissions:
  id-token: write
  contents: read  

jobs:
  build: 
    runs-on: ubuntu-latest
    env:
      rgName: "${{ vars.rgName }}"
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: AZ Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Azure Storage Account
        shell: bash
        run: |
          az deployment group create \
            --name deploySa \
            --resource-group "${{ vars.rgName }}" \
            --parameters ./infra/main.bicepparam

