name: Deploy Storage Account

on: workflow_dispatch

permissions:
  id-token: write
  contents: read  

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: AZ Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Azure Storage Account
        shell: pwsh
        run: |-
          az deployment sub create -n 'deploySa' -l 'uksouth' -f './infra/main.bicep' -p './infra/main.bicepparam'

